name: deploy to aws

on:
    workflow_dispatch:

jobs:
    aws_cdk:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with: 
                aws-access-key-id: ${{ secrets.TEST }}
                aws-secret-access-key: ${{ secrets.TEST }}
                aws-region: us-east-1
            - name: build and test
              uses: ./.github/workflows/build-full.yml
            - name: install npm
              run: 'sudo apt update -y && sudo apt install nodejs npm -y'
            - name: install AWS CDK