name: Dastardley scan

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run scan
      uses: PortSwigger/dastardly-github-action@main
      with: 
        target-url: 'http://localhost:3000'
    - name: Publish report
      uses: mikepenz/action-junit-report@v3
      with:
        check_name: 'Dastardly Scan Report'
        report_paths: '**/dastardly-report.xml'
        require_tests: false
